version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8000:80"
       #- "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

#   eaa_connector:
#     depends_on:
#       - wordpress
#     image: eaa_connector
#     restart: always

volumes:
    db_data: {}

networks:
   default: 
      driver: bridge
      ipam:
         driver: default
         config:
            - subnet: 172.18.0.0/24
              gateway: 172.18.0.1
